project_id = "jlbkacmbrjqejkdasbsj"

[functions.contact-submit]
verify_jwt = false

[functions.instagram-followers]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
